#!/usr/bin/env python3
"""Clean project-management language from the manuscript.

This script performs text-only manuscript cleanup. It does not alter analyses,
statistics, tables, or scientific conclusions.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MANUSCRIPT = ROOT / "manuscript" / "Communications_Biology_main_manuscript_v1.md"


REPLACEMENTS = {
    "under a locked analysis framework": "within a prespecified analytical framework",
    "This result closed the discrete-endotype route and prevented a categorical endotype claim.": "This result did not support a discrete-endotype interpretation and prevented a categorical endotype claim.",
    "This phase was deliberately placed before multisystem genetics to prevent interpreting genetic results through mutable transcriptomic labels.": "This test was performed before multisystem genetics to avoid interpreting genetic results through mutable transcriptomic labels.",
    "The Phase 4A genetic analysis tested genome-wide LDSC genetic correlation between overall psoriasis susceptibility and frozen comorbidity outcomes.": "The genome-wide genetic correlation analysis tested LDSC genetic correlation between overall psoriasis susceptibility and frozen comorbidity outcomes.",
    "Phase 4E then tested whether PP4-supported or suggestive coloc genes overlapped the frozen F1/F2/F6/F7 CORE/EXTENDED gene programs.": "We next tested whether PP4-supported or suggestive coloc genes overlapped the frozen F1/F2/F6/F7 CORE/EXTENDED gene programs.",
    "This study resolves the project into a layered model of psoriasis biology.": "This study supports a layered model of psoriasis biology.",
    "### Study design and analysis locks\n\nAll analyses were organized into sequential phases with frozen decision rules.": "### Study design and prespecified analysis framework\n\nAnalyses followed a prespecified sequence with predefined decision rules.",
    "final manuscript route": "prespecified analysis plan",
    "Processed result tables generated by this project are stored under the project `results/` and `manuscript/supplementary_tables/` directories.": "Processed result tables generated by this study are stored under the local `results/` and `manuscript/supplementary_tables/` directories.",
    "Restricted LAVA was applied only after Phase 4A and sign/QC adjudication.": "Restricted LAVA was applied only after genome-wide genetic correlation and sign/QC adjudication.",
    "By closing the axis-specific genetic route before testing comorbidities, the analysis avoids retrofitting genetic associations to flexible molecular labels.": "By completing the axis-specific genetic analysis before testing comorbidities, the analysis avoids retrofitting genetic associations to flexible molecular labels.",
}


def main() -> None:
    text = MANUSCRIPT.read_text(encoding="utf-8")
    for old, new in REPLACEMENTS.items():
        text = text.replace(old, new)
    MANUSCRIPT.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
